Output demo-kubectl-envx.gif

Set Theme "GitHub Dark"
Set FontSize 16
Set Width 650
Set Height 500
Set WindowBar Colorful
Set TypingSpeed 80ms
Set CursorBlink false
Set Padding 20

Hide
Type "clear"
Enter
Sleep 300ms
Show

Type "kubectl envx"
Sleep 2s
Enter
Sleep 2s

# Select kind: Deployment
Enter
Sleep 2s

# Select namespace
Type "ns-"
Sleep 600ms
Enter
Sleep 3s

# Select resource
Enter
Sleep 3s

Ctrl+C
Sleep 600ms
Type clear
Sleep 1s
