Output docs/assets/demo.gif

Set Theme "GitHub Dark"
Set FontSize 16
Set Width 650
Set Height 500
Set WindowBar Colorful
Set TypingSpeed 40ms
Set CursorBlink false
Set Padding 20

Hide
Type "clear"
Enter
Sleep 300ms
Show

Type "kenvx"
Enter
Sleep 500ms

# Select kind: Deployment
Enter
Sleep 3s

# Select namespace
Type "de"
Sleep 400ms
Down
Sleep 400ms
Enter
Sleep 3s

# Select resource
Enter
Sleep 3s

