from typing import Protocol

from kubek.kube.dto import WorkflowTemplate
from kubek.kube.dto.configmap import ConfigMap
from kubek.kube.dto.cronjob import CronJob
from kubek.kube.dto.daemonset import DaemonSet
from kubek.kube.dto.deployment import Deployment
from kubek.kube.dto.job import Job
from kubek.kube.dto.namespace import Namespace
from kubek.kube.dto.pod import Pod
from kubek.kube.dto.replicaset import ReplicaSet
from kubek.kube.dto.secret import Secret
from kubek.kube.dto.service import Service
from kubek.kube.dto.statefulset import StatefulSet


class ConfigMapRepository(Protocol):
    def get(self, name: str, namespace: str | None = None) -> ConfigMap | None: ...
    def list(self, namespace: str | None = None) -> list[ConfigMap]: ...


class DeploymentRepository(Protocol):
    def list(self, namespace: str | None = None) -> list[Deployment]: ...
    def get(self, name: str, namespace: str | None = None) -> Deployment | None: ...


class NamespaceRepository(Protocol):
    def list(self) -> list[Namespace]: ...
    def get(self, name: str) -> Namespace | None: ...


class PodRepository(Protocol):
    def list(self, namespace: str | None = None) -> list[Pod]: ...
    def get(self, name: str, namespace: str | None = None) -> Pod | None: ...


class SecretRepository(Protocol):
    def get(self, name: str, namespace: str | None = None) -> Secret | None: ...
    def list(self, namespace: str | None = None) -> list[Secret]: ...


class ServiceRepository(Protocol):
    def list(self, namespace: str | None = None) -> list[Service]: ...
    def get(self, name: str, namespace: str | None = None) -> Service | None: ...


class StatefulSetRepository(Protocol):
    def list(self, namespace: str | None = None) -> list[StatefulSet]: ...
    def get(self, name: str, namespace: str | None = None) -> StatefulSet | None: ...


class DaemonSetRepository(Protocol):
    def list(self, namespace: str | None = None) -> list[DaemonSet]: ...
    def get(self, name: str, namespace: str | None = None) -> DaemonSet | None: ...


class ReplicaSetRepository(Protocol):
    def list(self, namespace: str | None = None) -> list[ReplicaSet]: ...
    def get(self, name: str, namespace: str | None = None) -> ReplicaSet | None: ...


class JobRepository(Protocol):
    def list(self, namespace: str | None = None) -> list[Job]: ...
    def get(self, name: str, namespace: str | None = None) -> Job | None: ...


class CronJobRepository(Protocol):
    def list(self, namespace: str | None = None) -> list[CronJob]: ...
    def get(self, name: str, namespace: str | None = None) -> CronJob | None: ...


class WorkflowTemplateRepository(Protocol):
    def list(self, namespace: str | None = None) -> list[WorkflowTemplate]: ...
    def get(
        self, name: str, namespace: str | None = None
    ) -> WorkflowTemplate | None: ...
