default_namespace = "kube-public"

[[ports]]
name = "auth-service"
namespace = "kube-public"
remote_port = 80
local_port = 50000

[[ports]]
name = "user-service"
namespace = "kube-public"
remote_port = 8080
local_port = 50001